-- Create the table
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  content text not null
);

-- Set up Row Level Security (RLS)
alter table public.messages enable row level security;

-- Create Policy: Allow everyone to read messages
create policy "Enable read access for all users"
on public.messages for select
using (true);

-- Create Policy: Allow everyone to insert messages
create policy "Enable insert access for all users"
on public.messages for insert
with check (true);

-- Enable Realtime
alter publication supabase_realtime add table messages;
